language: python

python:
  - "2.7"
  - "3.6"

addons:
  apt:
    packages:
      - make
      - gcc
      - realpath

install:
  - pip install -r requirements.txt

script:
  - make
  - ./.travis.sh

notifications:
  email:
    on_success: never # default: change
