language: python

cache: pip

python:
  - "2.7"
  - "3.6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - make
      - gcc-7
      - g++-7
      - realpath

install:
  - pip install -r requirements.txt
  - pip install thunder/

script:
  - make
  - ./.travis.sh

notifications:
  email:
    on_success: never # default: change
