language: python

cache: pip

python:
  - "2.7"
  - "3.6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - make
      - gcc-7
      - g++-7
      - realpath

install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 99
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 99
  - pip install -r requirements.txt
  - pip install thunder/
  - pip install cyclone

script:
  - make
  - ./.travis.sh

notifications:
  email:
    on_success: never # default: change
