language: python

cache: pip

python:
  - "2.7"
  - "3.6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - make
      - g++-7
      - realpath
      - libxml2-dev
      - libigraph0-dev

install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 99
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 99
  - pip install -r requirements.txt
  - pip install thunder/
  - pip install cyclone/

script:
  - ./.travis.sh

after_success:
    - echo [distutils]                                  > ~/.pypirc
    - echo index-servers =                             >> ~/.pypirc
    - echo "  pypi"                                    >> ~/.pypirc
    - echo                                             >> ~/.pypirc
    - echo [pypi]                                      >> ~/.pypirc
    - echo repository=https://pypi.python.org/pypi     >> ~/.pypirc
    - echo username=keyi                               >> ~/.pypirc
    - echo password=$PYPI_PASSWORD                     >> ~/.pypirc

deploy:
  - provider: script
    script: /bin/sh scripts/deploy.sh
    on:
      # branch: master
      tags: false # true

notifications:
  email:
    on_success: never # default: change
